# Introduction to tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


## Creating tensor with tf.constant()

In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix with different dtype
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Creating tensor with tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try with unchangeable tensor
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Rarely in practice will you need to decide whether to use tf.constant or tf.Variable, as TensorFlow does this for me. Whaaat? I don't know how it does, but later on, I might see how it works.

## Creating random tensors

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in tensor

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 5],
                            [6, 7]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  7],
       [ 3,  5]], dtype=int32)>

In [ ]:
# run this cell multiple times, you will notice that it is still changing.
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 6,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  7],
       [10,  7]], dtype=int32)>

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

## Create tensor from numpy

In [ ]:
tf.ones([3, 2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([4, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run in GPU or TPU(tensor processing units)

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int16)
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [ ]:
# Add in extra dimension to rank 2 tensor
rank_2_tensor = tf.ones(shape=(2, 3))
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

## Manipulating tensors (tensor operations)

In [ ]:
tensor = tf.constant([[10, 7], [6, 5]])
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [16, 15]], dtype=int32)>

In [ ]:
tensor * 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140, 119],
       [112, 105]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  5]], dtype=int32)>

In [ ]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.7],
       [1.6, 1.5]])>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [160, 150]], dtype=int32)>

## Matrix multiplication

In [ ]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[672, 595],
       [560, 497]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [256, 225]], dtype=int32)>

Notice the difference

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[672, 595],
       [560, 497]], dtype=int32)>

In [ ]:
tf.tensordot(tensor, tensor, axes=1) # on the first axes

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[672, 595],
       [560, 497]], dtype=int32)>

In [ ]:
tf.reshape(tensor, shape=(1, 4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[20, 17, 16, 15]], dtype=int32)>

In [ ]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 16],
       [17, 15]], dtype=int32)>

To satisfy the matmul rule, always use transpose if you want change the shape of a matrix

## Changing the datatype

In [ ]:
B = tf.constant([1.5, 3.53])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5 , 3.53], dtype=float32)>

In [ ]:
# Change type to float16, the processing time is much faster with less memory
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5 , 3.53], dtype=float16)>

## Aggregating Tensors
Aggregating tensors = condensing them from multiple values down to smaller amount of values

In [ ]:
D = tf.constant([-10, -7])

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

Different forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([66, 38,  8, 16, 96, 47, 50,  8, 44, 14, 73, 73, 52,  5,  5, 76, 46,
       91, 94, 25,  9, 90, 82, 33, 85, 60, 32, 41, 15, 50, 83, 17, 46, 98,
       33, 62, 57, 58,  6, 27,  4, 60, 70, 24, 12, 37,  3, 77, 41, 14])>

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2253>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.85994529724121>

In [ ]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=832.8964233398438>

## Find the positional maximum and minimum

In [ ]:
tf.random.set_seed(0)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.29197514, 0.20656645, 0.53539073, 0.5612575 , 0.4166745 ,
       0.80782795, 0.4932251 , 0.99812925, 0.69673514, 0.1253736 ,
       0.7098167 , 0.6624156 , 0.57225657, 0.36475348, 0.42051828,
       0.630057  , 0.913813  , 0.6616472 , 0.83347356, 0.08395803,
       0.2797594 , 0.0155232 , 0.72637355, 0.7655387 , 0.6798667 ,
       0.53272796, 0.7565141 , 0.04742193, 0.05037141, 0.75174344,
       0.1727128 , 0.3119352 , 0.29137385, 0.10051239, 0.16567075,
       0.7696651 , 0.58567977, 0.98200965, 0.9148327 , 0.14166534,
       0.09756553, 0.6062784 , 0.17792177, 0.518052  , 0.9821211 ,
       0.17577946, 0.04563165, 0.59754145, 0.5629543 , 0.80507433],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9981292486190796>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

### Squezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(0)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.29197514, 0.20656645, 0.53539073, 0.5612575 , 0.4166745 ,
           0.80782795, 0.4932251 , 0.99812925, 0.69673514, 0.1253736 ,
           0.7098167 , 0.6624156 , 0.57225657, 0.36475348, 0.42051828,
           0.630057  , 0.913813  , 0.6616472 , 0.83347356, 0.08395803,
           0.2797594 , 0.0155232 , 0.72637355, 0.7655387 , 0.6798667 ,
           0.53272796, 0.7565141 , 0.04742193, 0.05037141, 0.75174344,
           0.1727128 , 0.3119352 , 0.29137385, 0.10051239, 0.16567075,
           0.7696651 , 0.58567977, 0.98200965, 0.9148327 , 0.14166534,
           0.09756553, 0.6062784 , 0.17792177, 0.518052  , 0.9821211 ,
           0.17577946, 0.04563165, 0.59754145, 0.5629543 , 0.80507433]]]]],
      dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.29197514, 0.20656645, 0.53539073, 0.5612575 , 0.4166745 ,
       0.80782795, 0.4932251 , 0.99812925, 0.69673514, 0.1253736 ,
       0.7098167 , 0.6624156 , 0.57225657, 0.36475348, 0.42051828,
       0.630057  , 0.913813  , 0.6616472 , 0.83347356, 0.08395803,
       0.2797594 , 0.0155232 , 0.72637355, 0.7655387 , 0.6798667 ,
       0.53272796, 0.7565141 , 0.04742193, 0.05037141, 0.75174344,
       0.1727128 , 0.3119352 , 0.29137385, 0.10051239, 0.16567075,
       0.7696651 , 0.58567977, 0.98200965, 0.9148327 , 0.14166534,
       0.09756553, 0.6062784 , 0.17792177, 0.518052  , 0.9821211 ,
       0.17577946, 0.04563165, 0.59754145, 0.5629543 , 0.80507433],
      dtype=float32)>

## One-hot encoding

In [ ]:
some_list = [0, 1, 2, 3] # could be red, green, blue, orange
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value='I love to dance', off_value='I love to sing')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love to dance', b'I love to sing', b'I love to sing',
        b'I love to sing'],
       [b'I love to sing', b'I love to dance', b'I love to sing',
        b'I love to sing'],
       [b'I love to sing', b'I love to sing', b'I love to dance',
        b'I love to sing'],
       [b'I love to sing', b'I love to sing', b'I love to sing',
        b'I love to dance']], dtype=object)>

In [ ]:
# Let's try changing the depth
tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

## Squaring, log, square root

In [ ]:
H = tf.range(1, 10)

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## The end of this notebook